### ISSUE TITLE
Cant use keyboard shortcuts to switch pane

### ISSUE THREAD

**Issue by QuentinDela** [domagojk/serverless-console#1] opened 2019-12-03 10:21 UTC
Hello, 

Thanks for this extension, it's pretty cool. 
Sometimes the switch panes shortcut won't work : Shift + Command + }

**Comment by domagojk** [comment] 2019-12-03 10:34
hey @QuentinDela 
I think I have different key bindings. So just to be sure, are you referring to
"workbench.action.switchWindow" command (as defined in "Keyboard Shortcut Preferences")?

**Comment by domagojk** [comment] 2020-01-17 10:43
I'm closing this since I wasn't able to reproduce it.
For anyone experiencing this, feel free to reopen the issue.

**Closed by domagojk** 2020-01-17 10:43 UTC
