### ISSUE TITLE
Bug: CloudWatch log name is not parsing correctly

### ISSUE THREAD

**Issue by Derek-X-Wang** [domagojk/serverless-console#31] opened 2020-09-04 09:16 UTC
doesn't seem it parse the name correctly from serverless.yml

![Screen Shot 2020-09-04 at 2 12 49 AM](https://user-images.githubusercontent.com/6364170/92222768-593c2980-ee54-11ea-9ca0-24a40556dfa9.png)
![Screen Shot 2020-09-04 at 2 13 40 AM](https://user-images.githubusercontent.com/6364170/92222774-5c371a00-ee54-11ea-9375-07231d31fdb9.png)

the correct name shall be `rtc-service-dev-websocket-heartbeat` in my case

**Comment by domagojk** [comment] 2020-09-07 07:02
@Derek-X-Wang Thanks for reporting! This should be fixed in ver 0.7.1

**Comment by domagojk** [comment] 2020-09-07 17:18
There was an error in ver 0.7.1. It should now work in 0.7.2

**Comment by Derek-X-Wang** [comment] 2020-09-09 01:04
it works. thx a lot

**Comment by Derek-X-Wang** [comment] 2020-09-12 08:56
![Screen Shot 2020-09-12 at 1 52 44 AM](https://user-images.githubusercontent.com/6364170/92991813-13f2aa00-f49b-11ea-9ae1-c636eb255a98.png)
![Screen Shot 2020-09-12 at 1 52 57 AM](https://user-images.githubusercontent.com/6364170/92991840-253bb680-f49b-11ea-829c-26636827b5fa.png)

another parse issue :) @domagojk

**Comment by domagojk** [comment] 2020-09-14 08:37
@Derek-X-Wang What would be a correct name in that case?
The extension now resolves it as expected (just as in the first example you posted): `${serviceName}-${stage}-${functionName}`

**Comment by icaptnbob** [comment] 2020-09-16 05:07
This extension is failing to find prod Cloud logs but works for dev stage. It was working at the end of August. Nothing has changed in the serverless.yml file since then. 
I keep getting this message when I go to the prod stage of any lambda function: "The specified log group does not exist."
The dev stage shows the current logs.

The prod stage logs are visible in AWS Cloudwatch for all of these.

This seems to coincide with this extension change. Is there anything I can do to debug?

**Comment by domagojk** [comment] 2020-09-16 06:33
I had to revert the extension to 0.7.0 since this fix obviously wasn't implemented correctly. I suspect this also has to do with serverless framework version.
@icaptnbob Can you please copy/paste your function definition from serverless.yml and also provide a serverless framework version you are using and I will try to debug the issue.

**Comment by icaptnbob** [comment] 2020-09-17 01:36
Hi Domagojk. Thanks for the very quick response.

Is this what you want?

npm list -depth 0
+-- serverless-bundle@1.4.0
+-- serverless-pseudo-parameters@2.5.0

serverless.yml (extract)
service: transact-drivers

plugins:
    - serverless-bundle
    - serverless-pseudo-parameters

custom:
    stage: ${opt:stage, self:provider.stage}
    resourcesStages:
        prod: prod
        dev: dev
    resourcesStage: ${self:custom.resourcesStages.${self:custom.stage}, self:custom.resourcesStages.dev}

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, 'dev'}
    region: eu-central-1

functions:
    # Driver Lambdas
    movacash-driver:
        handler: src/driver/movacash-driver.main
        vpc: ${self:custom.vpc}

    ecw-driver:
        handler: src/driver/ecw-driver.main
        vpc: ${self:custom.vpc}

    # Drivers Api
    list_driver:
        handler: src/driver/controller.listDriver
        events:
            - http:
                  path: driver/{driverName}
                  method: get
                  private: true

    list_drivers:
        handler: src/driver/controller.listDrivers
        events:
            - http:
                  path: driver
                  method: get
                  private: true

    driver_post:
        handler: src/driver/controller.executeDriverPost
        events:
            - http:
                  path: execute/{action} 
                  method: post
                  private: true

**Comment by Derek-X-Wang** [comment] 2020-09-17 04:52
Hi @domagojk, the correct name will be

**postConfirmation-dev**

for the name, there are two cases

1. default name, if the name field is not provided.
2. name filed is provided.

@icaptnbob using the default name and I use the explicit name.

for my case, 
stage is `dev`
service name is `user-service`
stackName is ${self:service}-${self:provider.stage} => `user-service-dev`

`name: postConfirmation-${self:provider.stage}` => `postConfirmation-dev`
`name: ${self:provider.stackName}-user-get` => `user-service-dev-user-get`

**Comment by domagojk** [comment] 2020-09-17 07:46
Thanks, @icaptnbob that's it 👍 

@Derek-X-Wang The problem is that I can't easily determine whether the explicit or implicit name is used (since `sls print` always shows as it was explicit). And also I can't just use explicit names since it should work for multiple stages which rely on `${serviceName}-${stage}-${functionName}` format. The only way I could use that is to execute `sls print` for every stage (also related to #10).

**Comment by Derek-X-Wang** [comment] 2020-09-17 09:04
@domagojk Here is the snippet of my sls print

so my difference with icaptnbob is I have `name` field

so if the name field exists. that shall be used as the log name and lambda name. if that is not present, that will be the default name.
```
functions:
  postCreateHandler:
    handler: src/post.create
    name: content-service-dev-post-create
    tags:
      rest: mobz post api
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        'Fn::Split':
          - ','
          - 'Fn::ImportValue': dev-private-subnets
    events: []
  postUpdateHandler:
    handler: src/post.update
    name: content-service-dev-post-update
    tags:
      rest: mobz post api
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        'Fn::Split':
          - ','
          - 'Fn::ImportValue': dev-private-subnets
    events: []
```

**Comment by domagojk** [comment] 2020-09-17 09:13
@Derek-X-Wang Again, the name field always exists. Na matter if you define it in serverless.yml or not, "sls print" will always show it. That property has a stage name included which is why it breaks for this extension (since "sls print" is evaluated only once, not for every stage)

**Comment by domagojk** [comment] 2020-09-22 13:55
@Derek-X-Wang Can you try out version 0.7.4?

Then in `.vscode/settings.json` rather than using `"command": "sls print"` try adding something like this:
```
"commandsPerStage": [
        {
          "stage": "dev",
          "command": "serverless print --stage dev"
        },
        {
          "stage": "prod",
          "command": "serverless print --stage prod"
        }
      ],
```

When `commandsPerStage` is defined the extension will run the command for each stage and use printed function name

**Comment by Derek-X-Wang** [comment] 2020-09-22 22:37
after I replace `"command": "sls print"` with `"commandsPerStage": []`. it works. 

so in the case when we add service via serverless, we need to update `.vscode/settings.json`?

**Comment by domagojk** [comment] 2020-09-23 08:19
> after I replace "command": "sls print" with "commandsPerStage": []. it works.

It works with an empty array and no command string? I really don't understand how that is possible. If array is empty, it should work as before (using `command`) and if you deleted that as well the extension doesn't have info on how to execute the print command. Can you share you settings.json for "serverlessConsole.services"?

> so in the case when we add service via serverless, we need to update .vscode/settings.json?

I haven't worked on UI yet, wanted to make sure it works first. So, for now - yes, you will have to edit settings.json. But using explicit names for function handlers like that is rarely done, so a default option should work fine for most users.

**Closed** 2020-11-26 07:44 UTC
